################
##  Sensores  ##
################
sensor:
  - platform: template
    sensors:
      windchill_invitados:
        value_template: "{{ (states('sensor.invitados_temperatura')|float + 0.348*(((states('sensor.invitados_humedad')|float/100)*6.105)*(2.71828**((17.27*states('sensor.invitados_temperatura')|float)/(237.7+states('sensor.invitados_temperatura')|float)))) - 4.25) | round(2) }}"
        friendly_name: Initados - Sensación térmica
        icon_template: mdi:thermometer-lines
        device_class: temperature   
        unit_of_measurement: '°C'

  - platform: mold_indicator
    name: Invitados Moho
    indoor_temp_sensor: sensor.invitados_temperatura
    indoor_humidity_sensor: sensor.invitados_humedad
    outdoor_temp_sensor: sensor.barcelona_temperature
    calibration_factor: 2.0
#calibration_factor = (temp_indoor - temp_outdoor) / (temp_criticalpoint - temp_outdoor)


#######################
##  Personalizacion  ##
#######################
homeassistant:
  customize:
    sensor.invitados_moho:
      icon: mdi:biohazard
