################
##  Sensores  ##
################
sensor:
  - platform: template
    sensors:
      windchill_cocina:
        value_template: "{{ (states('sensor.cocina_temperatura')|float + 0.348*(((states('sensor.cocina_humedad')|float/100)*6.105)*(2.71828**((17.27*states('sensor.cocina_temperatura')|float)/(237.7+states('sensor.cocina_temperatura')|float)))) - 4.25) | round(2) }}"
        friendly_name: Cocina - Sensación térmica
        icon_template: mdi:thermometer-lines
        device_class: temperature   
        unit_of_measurement: '°C'

  - platform: mold_indicator
    name: Cocina Moho
    indoor_temp_sensor: sensor.cocina_temperatura
    indoor_humidity_sensor: sensor.cocina_humedad
    outdoor_temp_sensor: sensor.barcelona_temperature
    calibration_factor: 2.0
#calibration_factor = (temp_indoor - temp_outdoor) / (temp_criticalpoint - temp_outdoor)


###############
##  Scripts  ##
###############
script:
     
 
########################
##  Automatizaciones  ##
########################
automation:


#########################
##  Personalizaciones  ##
#########################
homeassistant:
  customize:
    sensor.cocina_moho:
      icon: mdi:biohazard
